@include('admin.layout.header')
@include('admin.layout.navbar')
<div class="main-panel">
    <div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span> Parts Management
        </h3>
        <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
            <span></span>Update Parts Management<i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
            </li>
        </ul>
        </nav>
    </div>
    <div>
    <div>
<div>
    <div class="row">
        <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
            <h4 class="card-title">Update Item Details:</h4>
            <hr>

            <div id="dealer" class="tabcontent">
                <!-- <h3>Update Dealer</h3> -->
                <!-- form starting  -->
           <!-- Supplier Form -->
           @php($encryptedId = encrypt($part->id))
           <form method="POST" action="{{ url('partsinv/update/'.$encryptedId)}}" class="row" enctype="multipart/form-data">
           @csrf
                
                        <div class="col-12">
                            <hr>
                            <h4>Item Detail's :</h4>
                            <hr>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                        <label for="vehicle" class="form-label">{{ __('Product') }}<sup class="text-danger">*</sup></label>
                        <select id="vehicle" class="form-control p-3" name="vehicle" placeholder="" required autofocus>
                            <option value="">--Select Vehicle--</option>
                            <option value="pulsar"{{$part->vehicle == "pulsar" ? 'Selected' : ''}}>Pulsar</option>
                            <option value="discover"{{$part->vehicle == "discover" ? 'Selected' : ''}}>Discover</option>
                            <option value="platina"{{$part->vehicle == "platina" ? 'Selected' : ''}}>Platina</option>
                            <option value="avenger"{{$part->vehicle == "avenger" ? 'Selected' : ''}}>Avenger</option>
                            <option value="dominar"{{$part->vehicle == "dominar" ? 'Selected' : ''}}>Dominar</option>
                            <option value="ct_100"{{$part->vehicle == "ct_100" ? 'Selected' : ''}}>CT 100</option>
                            <option value="kratos"{{$part->vehicle == "kratos" ? 'Selected' : ''}}>Kratos</option>
                            <!-- Add more Bajaj bike types as needed -->
                        </select>
                        </div>



                        
                        <div class="mb-3 col-md-6 col-lg-3">
                          <label for="category" class="form-label">{{ __('Category') }}<sup class="text-danger">*</sup></label>
                          <select id="category" class="form-control p-3" name="category" placeholder="" required autofocus>
                              <option value="">--Select Category--</option>
                              @foreach($categories as $category)
                              @if($category->parent_id == 0)
                              @php($label = $category->category_name)
                              @php($parent_id = $category->id)
                              @endif 
                              <optgroup label="{{$label}}">
                              @foreach($sub_categories as $subcategory)
                              @if($parent_id == $subcategory->parent_id)
                                  <option value="{{$subcategory->category_name}}"{{$subcategory->category_name == $part->category ? 'Selected' : ''}}>{{$subcategory->category_name}}</option>
                                  @endif
                              @endforeach
                              </optgroup>
                              @endforeach
                              <!-- Add more Bajaj bike types as needed -->
                          </select>
                        </div>


                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="part_number" class="form-label">{{ __('Item Code') }}<sup class="text-danger">*</sup></label>
                            <input type="text" id="part_number" class="form-control" name="part_number" value="{{$part->part_number}}" placeholder="Part number will be auto generated by the system" required>
                        </div>

                        
                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="serial_number" class="form-label">{{ __('Serial Number') }}<sup class="text-danger">*</sup></label>
                            <input id="serial_number" type="text" class="form-control" name="serial_number" value="{{$part->serial_number}}" placeholder="For serialized parts, a unique serial number assigned to each unit." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="part_name" class="form-label">{{ __('Name') }}<sup class="text-danger">*</sup></label>
                            <input type="text" id="part_name" class="form-control p-3" name="part_name" value="{{$part->part_name}}" placeholder="Enter the name of the part" required autofocus>     
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="location" class="form-label">{{ __('Location') }}<sup class="text-danger">*</sup></label>
                            <input id="location" type="text" class="form-control" name="location" value="{{$part->location}}" placeholder="The physical location within the warehouse or storage facility where the part is stored." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="shelf_number" class="form-label">{{ __('Bin/Shelf Number') }}<sup class="text-danger">*</sup></label>
                            <input id="shelf_number" type="text" class="form-control" name="shelf_number" value="{{$part->shelf_number}}" placeholder="The specific bin or shelf number where the part is stored." required>
                        </div>


                        <div class="mb-3 col-md-6 col-lg-3">
                          <label for="availability" class="form-label">{{ __('Availability') }}</label>
                          <select id="availability" type="text" class="form-control p-3" name="availability">
                              <option value="">--Select--</option>
                              <option value="In Stock"{{$part->availability == 'In Stock' ? 'Selected' : ''}}>In Stock</option>
                              <option value="Out Of Stock"{{$part->availability == 'Out Of Stock' ? 'Selected' : ''}}>Out Of Stock</option>
                          </select>
                        </div>
                        

                        <div class="mb-3 col-md-6 col-lg-4">
                            <label for="part_description" class="form-label">{{ __('Part Description') }}</label>
                            <textarea id="part_description" rows="4" cols="50" type="text" class="form-control" name="part_description" placeholder="A brief description of the part, including its name, type, and specifications.">{{$part->part_description}}</textarea>
                        </div>


                        <!-- <div class="mb-3 col-md-6 col-lg-3">
                            <label for="reorder_point" class="form-label">{{ __('Reorder Point') }}</label>
                            <input id="reorder_point" type="text" class="form-control" name="reorder_point" placeholder="The minimum quantity of the part that triggers a reorder." required>
                        </div> -->

                        

                        <div class="mb-3 col-md-6 col-lg-4">
                            <label for="notes" class="form-label">{{ __('Notes') }}</label>
                            <textarea id="notes" type="text" rows="4" cols="50" class="form-control" name="notes" placeholder="Any additional notes or comments related to the part.">{{$part->notes}}</textarea>
                        </div>

                        <div class="mb-3 col-md-4">
                            <label for="warranty_information" class="form-label">{{ __('Warranty Information') }}</label>
                            <textarea id="warranty_information" rows="4" cols="50" type="text" class="form-control" name="warranty_information" placeholder=" Warranty details for the part, including warranty period and terms.">{{$part->warranty_description}}</textarea>
                        </div>


                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="condition" class="form-label">{{ __('Condition') }}<sup class="text-danger">*</sup></label>
                            <select id="condition" class="form-control p-3" name="condition" required autofocus>
                                <option value="">--Select The condition or status of the part (e.g., new, used, refurbished).--</option> 
                                <option value="New"{{$part->condition == 'New' ? 'Selected':''}}>New</option>
                                <option value="Used"{{$part->condition == 'Used' ? 'Selected':''}}>Used</option>
                                <option value="Refurbished"{{$part->condition == 'Refurbished' ? 'Selected':''}}>Refurbished</option>
                                
                            </select>
                        </div>


                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="unit_cost" class="form-label">{{ __('Unit Cost') }}<sup class="text-danger">*</sup></label>
                            <input id="unit_cost" type="text" value="{{$part->unit_cost}}" class="form-control" name="unit_cost" placeholder="The cost of purchasing one unit of the part." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="qty_on_hand" class="form-label">{{ __('Quantity On Hand') }}<sup class="text-danger">*</sup></label>
                            <input id="qty_on_hand" value="{{$part->qty_on_hand}}" type="text" class="form-control" name="qty_on_hand" placeholder="The current quantity of the part available in inventory." required>
                        </div>

                        
                        <!-- <div class="mb-3 col-md-6 col-lg-3">
                            <label for="category" class="form-label">{{ __('Category') }}</label>
                            <select id="category" class="form-control p-3" name="category" placeholder="The category or classification of the part (e.g., engine parts, body parts, electrical components)." required autofocus>
                                <option value="">--Selecty Category--</option> 
                                <option value="engine_parts">Engine Parts</option>
                                <option value="body_parts">Body Parts</option>
                                <option value="electrical_components">Electrical Components</option>
                                <option value="suspension_systems">Suspension Systems</option>
                                <option value="braking_systems">Braking Systems</option>
                                <option value="transmission_parts">Transmission Parts</option>
                                <option value="interior_accessories">Interior Accessories</option>
                                <option value="exterior_accessories">Exterior Accessories</option>
                            </select>
                        </div> -->


                        <!-- <div class="mb-3 col-md-6 col-lg-3">
                            <label for="manufacturer" class="form-label">{{ __('Manufacturer') }}</label>
                            <input type="text" id="manufacturer" class="form-control" name="manufacturer" placeholder="The manufacturer or brand of the part." required>
                        </div> -->


                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="min_stock_level" class="form-label">{{ __('Minimum Stock Level') }}<sup class="text-danger">*</sup></label>
                            <input id="min_stock_level" value="{{$part->min_stock_level}}" type="text" class="form-control" name="min_stock_level" placeholder="The minimum stock level for the part to ensure availability." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="max_stock_level" class="form-label">{{ __('Maximum Stock Level') }}<sup class="text-danger">*</sup></label>
                            <input id="max_stock_level" value="{{$part->max_stock_level}}" type="text" class="form-control" name="max_stock_level" placeholder="The maximum stock level for the part to ensure availability." required>
                        </div>

                        

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="compatability" class="form-label">{{ __('Compatability') }}</label>
                            <input id="compatability" value="{{$part->compatability}}" type="text" class="form-control" name="compatability" placeholder="Compatibility information indicating which vehicles or models the part is compatible with." >
                        </div>



                        <div class="mb-3 col-md-6">
                            <label for="image" class="form-label">{{ __('Image') }}</label>
                            <input id="image" type="file" class="form-control" name="image">
                            <p class="text-info">Images or photographs of the part for visual identification</p>
                        </div>


                        <div class="col-12">
                        <hr>
                        <h4>Supplier Detail's :</h4>
                        <hr>
                        </div>
                        
                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="supplier_id" class="form-label">{{ __('Supplier') }}<sup class="text-danger">*</sup></label>
                            <select id="supplier_id" class="form-control p-3" name="supplier_id" placeholder="The category or classification of the part (e.g., engine parts, body parts, electrical components)." required autofocus>
                                <option value="">--Select Supplier--</option> 
                                <option value="engine_parts"{{$part->supplier_id == "engine_parts" ? 'Selected' : ''}}>supplier 1</option>
                                <option value="body_parts"{{$part->supplier_id == "body_parts" ? 'Selected' : ''}}>supplier 2</option>
                                <option value="electrical_components"{{$part->supplier_id == "electrical_components" ? 'Selected' : ''}}>supplier 3</option>
                                <option value="suspension_systems"{{$part->supplier_id == "suspension_systems" ? 'Selected' : ''}}>supplier 4</option>
                            </select>
                        </div>


                        
                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="lead_time" class="form-label">{{ __('Delivery Date') }}</label>
                            <input id="lead_time" value="{{$part->lead_time}}" type="date" class="form-control" name="lead_time" placeholder=" The lead time or delivery time for replenishing the part from the supplier.">
                        </div>

                        <div class="col-12"><hr></div>


                        
                        <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Submit') }}
                        </button>
                        </div>
                    </form>
<!--                    
</div>
</div>
                    </div> -->
            <!-- <p class="card-description"> Add class <code>.table</code>
            </p> -->
            </div>
            </div>
        </div>
    </div>

    </div>
        
    </div>
</div>
</div>
</div>
          <!-- content-wrapper ends -->
@include('admin.layout.footer')

