@include('admin.layout.header')
@include('admin.layout.navbar')
<div class="main-panel">
    <div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-home"></i>
        </span> Goods Recieving Note's
        </h3>
        <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
            <span></span>Update Goods Recieving Note's<i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
            </li>
        </ul>
        </nav>
    </div>
    <div>
    <div>
<div>
    <div class="row">
        <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
            <h4 class="card-title">Update Goods Recieving Note's:</h4>
            <hr>

            <div id="dealer" class="tabcontent">
                <!-- <h3>Update Dealer</h3> -->
                <!-- form starting  -->
           <!-- Supplier Form -->
           @php($encryptedId = encrypt($allocation->id))
           <form method="POST" action="{{ url('sra/update/'.$encryptedId)}}" class="row">
                        @csrf
                        <div class="col-12">
                            <hr>
                            <h4>Item Detail's :</h4>
                            <hr>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="inventory_id" class="form-label">{{ __('Inventory ID') }}<sup class="text-danger">*</sup></label>
                            <input type="text" value="{{$allocation->inventory_id}}" id="inventory_id" class="form-control" name="inventory_id" value="INVID_{{rand(0,999999)}}" placeholder="A unique identifier for each inventory item." required>
                        </div>


                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="part_number" class="form-label">{{ __('Item Code') }}<sup class="text-danger">*</sup></label>
                            <input value="{{$allocation->item_code}}" list="part_number_list" id="part_number" class="form-control" name="part_number" placeholder="Part number will be auto generated by the system" required>
                            <datalist id="part_number_list">
                                @foreach($parts as $part)
                                    <option value="{{$part->part_number}}">
                                @endforeach
                                <!-- Add more options as needed -->
                            </datalist>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                        <label for="vehicle" class="form-label">{{ __('Product') }}<sup class="text-danger">*</sup></label>
                        <select id="vehicle" class="form-control p-3" name="vehicle" placeholder="" required autofocus>
                            <option value="">--Select Vehicle--</option>
                            <option value="pulsar"{{$allocation->category == 'pulsar' ? 'Selected' : ''}}>Pulsar</option>
                            <option value="discover"{{$allocation->category == 'discover' ? 'Selected' : ''}}>Discover</option>
                            <option value="platina"{{$allocation->category == 'platina' ? 'Selected' : ''}}>Platina</option>
                            <option value="avenger"{{$allocation->category == 'avenger' ? 'Selected' : ''}}>Avenger</option>
                            <option value="dominar"{{$allocation->category == 'dominar' ? 'Selected' : ''}}>Dominar</option>
                            <option value="ct_100"{{$allocation->category == 'ct_100' ? 'Selected' : ''}}>CT 100</option>
                            <option value="kratos"{{$allocation->category == 'kratos' ? 'Selected' : ''}}>Kratos</option>
                            <!-- Add more Bajaj bike types as needed -->
                        </select>
                        </div>
                        

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="location" class="form-label">{{ __('Location') }}<sup class="text-danger">*</sup></label>
                            <input id="location" value="{{$allocation->location}}" type="text" class="form-control" name="location" placeholder="The physical location within the warehouse or storage facility where the part is stored." required>
                        </div>


                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="current_stock_level" class="form-label">{{ __('Current Stock Level') }}<sup class="text-danger">*</sup></label>
                            <input id="current_stock_level" value="{{$allocation->current_stock_level}}" type="text" class="form-control" name="current_stock_level" placeholder="The current stock level for the part to ensure availability." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="min_stock_level" class="form-label">{{ __('Minimum Stock Level') }}<sup class="text-danger">*</sup></label>
                            <input id="min_stock_level" value="{{$allocation->min_stock_level}}" type="text" class="form-control" name="min_stock_level" placeholder="The minimum stock level for the part to ensure availability." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="max_stock_level" class="form-label">{{ __('Maximum Stock Level') }}<sup class="text-danger">*</sup></label>
                            <input id="max_stock_level" value="{{$allocation->max_stock_level}}" type="text" class="form-control" name="max_stock_level" placeholder="The maximum stock level for the part to ensure availability." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="reorder_point" class="form-label">{{ __('Reorder Point') }}<sup class="text-danger">*</sup></label>
                            <input id="reorder_point" value="{{$allocation->reorder_point}}" type="text" class="form-control" name="reorder_point" placeholder="The inventory level at which a reorder of the item should be triggered." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="lead_time" class="form-label">{{ __('Lead Time') }}<sup class="text-danger">*</sup></label>
                            <input id="lead_time" value="{{$allocation->lead_time}}" type="text" class="form-control" name="lead_time" placeholder="The lead time or delivery time for replenishing the inventory item from the supplier." required>
                        </div>
                        
                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="last_replenishment_date" class="form-label">{{ __('Last Replenishment date') }}<sup class="text-danger">*</sup></label>
                            <input id="last_replenishment_date" value="{{$allocation->last_replenishment_date}}" type="date" class="form-control" name="last_replenishment_date" placeholder="The date when the inventory item was last replenished." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="demand_forecast" class="form-label">{{ __('Demand Forecast') }}<sup class="text-danger">*</sup></label>
                            <input id="demand_forecast" value="{{$allocation->demand_forecast}}" type="text" class="form-control" name="demand_forecast" placeholder="Forecasted demand for the inventory item over a specific period." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="sales_channels" class="form-label">{{ __('Sales Channels') }}<sup class="text-danger">*</sup></label>
                            <input id="sales_channels" type="text" value="{{$allocation->sales_channels}}" class="form-control" name="sales_channels" placeholder="The sales channel or distribution channel through which the inventory item is sold (e.g., retail stores, online marketplace)." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="allocation_qty" class="form-label">{{ __('Allocation Quantity') }}<sup class="text-danger">*</sup></label>
                            <input id="allocation_qty" value="{{$allocation->allocation_qty}}" type="text" class="form-control" name="allocation_qty" placeholder="The quantity of the inventory item allocated to a specific sales channel, location, or order." required>
                        </div>
                        

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="allocation_date" class="form-label">{{ __('Allocation Date') }}<sup class="text-danger">*</sup></label>
                            <input id="allocation_date" value="{{$allocation->alloation_date}}" type="date" class="form-control" name="allocation_date" placeholder="The date when the inventory item was allocated." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="location" class="form-label">{{ __('Allocated Location') }}<sup class="text-danger">*</sup></label>
                            <input id="location" value="{{$allocation->location}}" type="text" class="form-control" name="location" placeholder="The maximum stock level for the part to ensure availability." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="demand_variability" class="form-label">{{ __('Demand Variability') }}<sup class="text-danger">*</sup></label>
                            <input id="demand_variability" value="{{$allocation->demand_variability}}" type="text" class="form-control" name="demand_variability" placeholder="Variability in demand for the inventory item, based on factors such as seasonality, promotions, and market trends." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="safety_stock" class="form-label">{{ __('Safety Stock') }}<sup class="text-danger">*</sup></label>
                            <input id="safety_stock" value="{{$allocation->safety_stock}}" type="text" class="form-control" name="safety_stock" placeholder="Additional stock held as a buffer to mitigate the risk of stockouts due to demand variability or lead time variability." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="order_qty" class="form-label">{{ __('Order Quantity') }}<sup class="text-danger">*</sup></label>
                            <input id="order_qty" value="{{$allocation->order_qty}}" type="text" class="form-control" name="order_qty" placeholder="The quantity of the inventory item to be ordered for replenishment, calculated based on factors such as demand forecast, lead time, and safety stock." required>
                        </div>

                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="availability" class="form-label">{{ __('Availability') }}<sup class="text-danger">*</sup></label>
                            <input id="availability" value="{{$allocation->availability}}" type="text" class="form-control" name="availability" placeholder="Information about the availability of the inventory item for sale or use, including current stock levels and allocations." required>
                        </div>

                        <div class="mb-3 col-md-6">
                            <label for="part_description" class="form-label">{{ __('Part Description') }}</label>
                            <textarea id="part_description" rows="4" cols="50" type="text" class="form-control" name="part_description" placeholder="A brief description of the part, including its name, type, and specifications.">{{$allocation->description}}</textarea>
                        </div>

                  


                        <div class="col-12">
                        <hr>
                        <h4>Supplier Detail's :</h4>
                        <hr>
                        </div>
                        
                        <div class="mb-3 col-md-6 col-lg-3">
                            <label for="supplier_id" class="form-label">{{ __('Supplier') }}<sup class="text-danger">*</sup></label>
                            <select id="supplier_id" class="form-control p-3" name="supplier_id" placeholder="The category or classification of the part (e.g., engine parts, body parts, electrical components)." required autofocus>
                                <option value="">--Select Supplier--</option> 
                                <option value="Abhishek"{{$allocation->supplier == 'Abhishek' ? 'Selected' : ''}}>Abhishek</option>
                                <option value="Priyanka"{{$allocation->supplier == 'Priyanka' ? 'Selected' : ''}}>Priyanka</option>
                                <option value="Kalpana"{{$allocation->supplier == 'Kalpana' ? 'Selected' : ''}}>Kalpana</option>
                                <option value="Arush"{{$allocation->supplier == 'Arush' ? 'Selected' : ''}}>Arush</option>
                            </select>
                        </div>

                        <div class="col-12"><hr></div>

                        <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Submit') }}
                        </button>
                        </div>
                    </form>
<!--                    
</div>
</div>
                    </div> -->
            <!-- <p class="card-description"> Add class <code>.table</code>
            </p> -->
            </div>
            </div>
        </div>
    </div>

    </div>
        
    </div>
</div>
</div>
</div>
          <!-- content-wrapper ends -->
@include('admin.layout.footer')

